server:
  port: 8094

#Admin configuration
info:
  name: career-ms
  description: career-ms
  version: 1.0.7-SNAPSHOT
  stage: local


spring:
  application:
    id: career-ms
    name: career-ms
  jpa:
    properties:
      hibernate:
        default_schema: ${datasource.db.schema}
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: ${datasource.db.platform}
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.db.driver}
  liquibase:
    default-schema: ${datasource.db.schema}
    change-log: classpath:config/db/db.changelog-master.xml
    contexts: postgres
  profiles.active: local
  boot:
    admin:
      client:
        url: ${boot.admin.client.url}
        username: ${boot.admin.client.username}
        password: ${boot.admin.client.password}
        instance:
          metadata:
            enable-oauth2: true

  security:
    actuator:
      password: easymsActuatorPass!

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

td.ms.url: localhost:8093
hr.ms.url: localhost:8092
search.ms.url: localhost:8102

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA39Zg3MUX3hIi7UnAPnZOerwpHMX7jC4BitiwCM11nSpawR/NvQGaI6Ej1NURHgn9kYpuoVUplS//GyTMTHd3G4h0Dh89tE8uR7V6XNw9qSJsYXF02xJ2MZxeP2G9UdEvWq13kJzxi+qXziHRPCAK5GVDOxEZmxILUA8kLw7i3d8T3g8+hAge5B0sc32wbF1NhRa+u7vK2uSIx+bxyah48Qw/y0Xqk+eLtcsVnXqD0cwEfgoMrcxfs1L/3vYdQ9U0Q/tvWnPrK2HFaGzPfWPr86ieB+yotnec0I9G60Rekq8ebW1vYqZCEG1BpELN9cVTHwSJ17iWHihfMqMrV/dIcwIDAQAB
          -----END PUBLIC KEY-----

swagger:
  paths: /api.*
  security:
    oauth2:
      client:
        clientId: swagger-platform
        clientSecret: secret
  securityDefinitions:
    oauthSecurity:
      type: oauth2
      tokenUrl: http://localhost:2000/oauth/token
      flow: password
      scopes:

easyms:
  secured: true
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfig
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512

management.endpoints.web.exposure.include: "*"

---
spring:
  profiles: sample


---
spring:
  liquibase:
    default-schema: career
    contexts: testData
  profiles: h2
  jpa:
    properties:
      hibernate:
        default_schema: career
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:career;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:config/db/h2-init.sql';
    username: career
    password: secret
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
    path: /h2-console

---
spring:
  liquibase:
    contexts: testData
  profiles: test
  jpa:
    hibernate.ddl-auto: none
  h2.console.enabled: false
  boot:
    admin:
      client:
        enabled: false

spring.profiles.include:
  - h2

liquibase.contexts: testData

---
spring:
  profiles: azure-vault

azure:
  keyvault:
    enabled: true
    uri: https://keyvault-access-tokens.vault.azure.net/
    client-id: 14f310f7-c3b9-4f1a-b746-2434b6bc7ecc
    tenant-id: 3cf74170-97e2-4f3a-ba67-480a9ec41fb2
    client-key: XX0pJslRndE6~oIVB-I~.i7U6S6x9dSQy.
    token-acquire-timeout-seconds: 60
    refresh-interval: 1800000
